// Code generated by capnpc-go. DO NOT EDIT.

package rpc

import (
	context "golang.org/x/net/context"
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
	server "zombiezen.com/go/capnproto2/server"
)

type MixnetConfig struct{ capnp.Struct }

// MixnetConfig_TypeID is the unique identifier for the type MixnetConfig.
const MixnetConfig_TypeID = 0x95896509ee825aa6

func NewMixnetConfig(s *capnp.Segment) (MixnetConfig, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return MixnetConfig{st}, err
}

func NewRootMixnetConfig(s *capnp.Segment) (MixnetConfig, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return MixnetConfig{st}, err
}

func ReadRootMixnetConfig(msg *capnp.Message) (MixnetConfig, error) {
	root, err := msg.RootPtr()
	return MixnetConfig{root.Struct()}, err
}

func (s MixnetConfig) String() string {
	str, _ := text.Marshal(0x95896509ee825aa6, s.Struct)
	return str
}

func (s MixnetConfig) SecondsToNextRound() uint16 {
	return s.Struct.Uint16(0)
}

func (s MixnetConfig) SetSecondsToNextRound(v uint16) {
	s.Struct.SetUint16(0, v)
}

// MixnetConfig_List is a list of MixnetConfig.
type MixnetConfig_List struct{ capnp.List }

// NewMixnetConfig creates a new list of MixnetConfig.
func NewMixnetConfig_List(s *capnp.Segment, sz int32) (MixnetConfig_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return MixnetConfig_List{l}, err
}

func (s MixnetConfig_List) At(i int) MixnetConfig { return MixnetConfig{s.List.Struct(i)} }

func (s MixnetConfig_List) Set(i int, v MixnetConfig) error { return s.List.SetStruct(i, v.Struct) }

func (s MixnetConfig_List) String() string {
	str, _ := text.MarshalList(0x95896509ee825aa6, s.List)
	return str
}

// MixnetConfig_Promise is a wrapper for a MixnetConfig promised by a client call.
type MixnetConfig_Promise struct{ *capnp.Pipeline }

func (p MixnetConfig_Promise) Struct() (MixnetConfig, error) {
	s, err := p.Pipeline.Struct()
	return MixnetConfig{s}, err
}

type ConvoMsg struct{ capnp.Struct }

// ConvoMsg_TypeID is the unique identifier for the type ConvoMsg.
const ConvoMsg_TypeID = 0xe4fb25d5577e606e

func NewConvoMsg(s *capnp.Segment) (ConvoMsg, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ConvoMsg{st}, err
}

func NewRootConvoMsg(s *capnp.Segment) (ConvoMsg, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ConvoMsg{st}, err
}

func ReadRootConvoMsg(msg *capnp.Message) (ConvoMsg, error) {
	root, err := msg.RootPtr()
	return ConvoMsg{root.Struct()}, err
}

func (s ConvoMsg) String() string {
	str, _ := text.Marshal(0xe4fb25d5577e606e, s.Struct)
	return str
}

func (s ConvoMsg) Content() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return []byte(p.Data()), err
}

func (s ConvoMsg) HasContent() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s ConvoMsg) SetContent(v []byte) error {
	return s.Struct.SetData(0, v)
}

// ConvoMsg_List is a list of ConvoMsg.
type ConvoMsg_List struct{ capnp.List }

// NewConvoMsg creates a new list of ConvoMsg.
func NewConvoMsg_List(s *capnp.Segment, sz int32) (ConvoMsg_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return ConvoMsg_List{l}, err
}

func (s ConvoMsg_List) At(i int) ConvoMsg { return ConvoMsg{s.List.Struct(i)} }

func (s ConvoMsg_List) Set(i int, v ConvoMsg) error { return s.List.SetStruct(i, v.Struct) }

func (s ConvoMsg_List) String() string {
	str, _ := text.MarshalList(0xe4fb25d5577e606e, s.List)
	return str
}

// ConvoMsg_Promise is a wrapper for a ConvoMsg promised by a client call.
type ConvoMsg_Promise struct{ *capnp.Pipeline }

func (p ConvoMsg_Promise) Struct() (ConvoMsg, error) {
	s, err := p.Pipeline.Struct()
	return ConvoMsg{s}, err
}

type EntryMix struct{ Client capnp.Client }

// EntryMix_TypeID is the unique identifier for the type EntryMix.
const EntryMix_TypeID = 0xe484a44c3b1b3577

func (c EntryMix) GetMixnetConfig(ctx context.Context, params func(EntryMix_getMixnetConfig_Params) error, opts ...capnp.CallOption) EntryMix_getMixnetConfig_Results_Promise {
	if c.Client == nil {
		return EntryMix_getMixnetConfig_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xe484a44c3b1b3577,
			MethodID:      0,
			InterfaceName: "rpc/entry.capnp:EntryMix",
			MethodName:    "getMixnetConfig",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		call.ParamsFunc = func(s capnp.Struct) error { return params(EntryMix_getMixnetConfig_Params{Struct: s}) }
	}
	return EntryMix_getMixnetConfig_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c EntryMix) AddConvoMsg(ctx context.Context, params func(EntryMix_addConvoMsg_Params) error, opts ...capnp.CallOption) EntryMix_addConvoMsg_Results_Promise {
	if c.Client == nil {
		return EntryMix_addConvoMsg_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xe484a44c3b1b3577,
			MethodID:      1,
			InterfaceName: "rpc/entry.capnp:EntryMix",
			MethodName:    "addConvoMsg",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		call.ParamsFunc = func(s capnp.Struct) error { return params(EntryMix_addConvoMsg_Params{Struct: s}) }
	}
	return EntryMix_addConvoMsg_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}

type EntryMix_Server interface {
	GetMixnetConfig(EntryMix_getMixnetConfig) error

	AddConvoMsg(EntryMix_addConvoMsg) error
}

func EntryMix_ServerToClient(s EntryMix_Server) EntryMix {
	c, _ := s.(server.Closer)
	return EntryMix{Client: server.New(EntryMix_Methods(nil, s), c)}
}

func EntryMix_Methods(methods []server.Method, s EntryMix_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe484a44c3b1b3577,
			MethodID:      0,
			InterfaceName: "rpc/entry.capnp:EntryMix",
			MethodName:    "getMixnetConfig",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := EntryMix_getMixnetConfig{c, opts, EntryMix_getMixnetConfig_Params{Struct: p}, EntryMix_getMixnetConfig_Results{Struct: r}}
			return s.GetMixnetConfig(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe484a44c3b1b3577,
			MethodID:      1,
			InterfaceName: "rpc/entry.capnp:EntryMix",
			MethodName:    "addConvoMsg",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := EntryMix_addConvoMsg{c, opts, EntryMix_addConvoMsg_Params{Struct: p}, EntryMix_addConvoMsg_Results{Struct: r}}
			return s.AddConvoMsg(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 0},
	})

	return methods
}

// EntryMix_getMixnetConfig holds the arguments for a server call to EntryMix.getMixnetConfig.
type EntryMix_getMixnetConfig struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  EntryMix_getMixnetConfig_Params
	Results EntryMix_getMixnetConfig_Results
}

// EntryMix_addConvoMsg holds the arguments for a server call to EntryMix.addConvoMsg.
type EntryMix_addConvoMsg struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  EntryMix_addConvoMsg_Params
	Results EntryMix_addConvoMsg_Results
}

type EntryMix_getMixnetConfig_Params struct{ capnp.Struct }

// EntryMix_getMixnetConfig_Params_TypeID is the unique identifier for the type EntryMix_getMixnetConfig_Params.
const EntryMix_getMixnetConfig_Params_TypeID = 0xa95371b6f84fa998

func NewEntryMix_getMixnetConfig_Params(s *capnp.Segment) (EntryMix_getMixnetConfig_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EntryMix_getMixnetConfig_Params{st}, err
}

func NewRootEntryMix_getMixnetConfig_Params(s *capnp.Segment) (EntryMix_getMixnetConfig_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EntryMix_getMixnetConfig_Params{st}, err
}

func ReadRootEntryMix_getMixnetConfig_Params(msg *capnp.Message) (EntryMix_getMixnetConfig_Params, error) {
	root, err := msg.RootPtr()
	return EntryMix_getMixnetConfig_Params{root.Struct()}, err
}

func (s EntryMix_getMixnetConfig_Params) String() string {
	str, _ := text.Marshal(0xa95371b6f84fa998, s.Struct)
	return str
}

// EntryMix_getMixnetConfig_Params_List is a list of EntryMix_getMixnetConfig_Params.
type EntryMix_getMixnetConfig_Params_List struct{ capnp.List }

// NewEntryMix_getMixnetConfig_Params creates a new list of EntryMix_getMixnetConfig_Params.
func NewEntryMix_getMixnetConfig_Params_List(s *capnp.Segment, sz int32) (EntryMix_getMixnetConfig_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return EntryMix_getMixnetConfig_Params_List{l}, err
}

func (s EntryMix_getMixnetConfig_Params_List) At(i int) EntryMix_getMixnetConfig_Params {
	return EntryMix_getMixnetConfig_Params{s.List.Struct(i)}
}

func (s EntryMix_getMixnetConfig_Params_List) Set(i int, v EntryMix_getMixnetConfig_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s EntryMix_getMixnetConfig_Params_List) String() string {
	str, _ := text.MarshalList(0xa95371b6f84fa998, s.List)
	return str
}

// EntryMix_getMixnetConfig_Params_Promise is a wrapper for a EntryMix_getMixnetConfig_Params promised by a client call.
type EntryMix_getMixnetConfig_Params_Promise struct{ *capnp.Pipeline }

func (p EntryMix_getMixnetConfig_Params_Promise) Struct() (EntryMix_getMixnetConfig_Params, error) {
	s, err := p.Pipeline.Struct()
	return EntryMix_getMixnetConfig_Params{s}, err
}

type EntryMix_getMixnetConfig_Results struct{ capnp.Struct }

// EntryMix_getMixnetConfig_Results_TypeID is the unique identifier for the type EntryMix_getMixnetConfig_Results.
const EntryMix_getMixnetConfig_Results_TypeID = 0xcdf3f95e02d5f38e

func NewEntryMix_getMixnetConfig_Results(s *capnp.Segment) (EntryMix_getMixnetConfig_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EntryMix_getMixnetConfig_Results{st}, err
}

func NewRootEntryMix_getMixnetConfig_Results(s *capnp.Segment) (EntryMix_getMixnetConfig_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EntryMix_getMixnetConfig_Results{st}, err
}

func ReadRootEntryMix_getMixnetConfig_Results(msg *capnp.Message) (EntryMix_getMixnetConfig_Results, error) {
	root, err := msg.RootPtr()
	return EntryMix_getMixnetConfig_Results{root.Struct()}, err
}

func (s EntryMix_getMixnetConfig_Results) String() string {
	str, _ := text.Marshal(0xcdf3f95e02d5f38e, s.Struct)
	return str
}

func (s EntryMix_getMixnetConfig_Results) Meta() (MixnetConfig, error) {
	p, err := s.Struct.Ptr(0)
	return MixnetConfig{Struct: p.Struct()}, err
}

func (s EntryMix_getMixnetConfig_Results) HasMeta() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s EntryMix_getMixnetConfig_Results) SetMeta(v MixnetConfig) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewMeta sets the meta field to a newly
// allocated MixnetConfig struct, preferring placement in s's segment.
func (s EntryMix_getMixnetConfig_Results) NewMeta() (MixnetConfig, error) {
	ss, err := NewMixnetConfig(s.Struct.Segment())
	if err != nil {
		return MixnetConfig{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// EntryMix_getMixnetConfig_Results_List is a list of EntryMix_getMixnetConfig_Results.
type EntryMix_getMixnetConfig_Results_List struct{ capnp.List }

// NewEntryMix_getMixnetConfig_Results creates a new list of EntryMix_getMixnetConfig_Results.
func NewEntryMix_getMixnetConfig_Results_List(s *capnp.Segment, sz int32) (EntryMix_getMixnetConfig_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return EntryMix_getMixnetConfig_Results_List{l}, err
}

func (s EntryMix_getMixnetConfig_Results_List) At(i int) EntryMix_getMixnetConfig_Results {
	return EntryMix_getMixnetConfig_Results{s.List.Struct(i)}
}

func (s EntryMix_getMixnetConfig_Results_List) Set(i int, v EntryMix_getMixnetConfig_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s EntryMix_getMixnetConfig_Results_List) String() string {
	str, _ := text.MarshalList(0xcdf3f95e02d5f38e, s.List)
	return str
}

// EntryMix_getMixnetConfig_Results_Promise is a wrapper for a EntryMix_getMixnetConfig_Results promised by a client call.
type EntryMix_getMixnetConfig_Results_Promise struct{ *capnp.Pipeline }

func (p EntryMix_getMixnetConfig_Results_Promise) Struct() (EntryMix_getMixnetConfig_Results, error) {
	s, err := p.Pipeline.Struct()
	return EntryMix_getMixnetConfig_Results{s}, err
}

func (p EntryMix_getMixnetConfig_Results_Promise) Meta() MixnetConfig_Promise {
	return MixnetConfig_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

type EntryMix_addConvoMsg_Params struct{ capnp.Struct }

// EntryMix_addConvoMsg_Params_TypeID is the unique identifier for the type EntryMix_addConvoMsg_Params.
const EntryMix_addConvoMsg_Params_TypeID = 0xfd26198720563ad2

func NewEntryMix_addConvoMsg_Params(s *capnp.Segment) (EntryMix_addConvoMsg_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EntryMix_addConvoMsg_Params{st}, err
}

func NewRootEntryMix_addConvoMsg_Params(s *capnp.Segment) (EntryMix_addConvoMsg_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EntryMix_addConvoMsg_Params{st}, err
}

func ReadRootEntryMix_addConvoMsg_Params(msg *capnp.Message) (EntryMix_addConvoMsg_Params, error) {
	root, err := msg.RootPtr()
	return EntryMix_addConvoMsg_Params{root.Struct()}, err
}

func (s EntryMix_addConvoMsg_Params) String() string {
	str, _ := text.Marshal(0xfd26198720563ad2, s.Struct)
	return str
}

func (s EntryMix_addConvoMsg_Params) Msg() (ConvoMsg, error) {
	p, err := s.Struct.Ptr(0)
	return ConvoMsg{Struct: p.Struct()}, err
}

func (s EntryMix_addConvoMsg_Params) HasMsg() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s EntryMix_addConvoMsg_Params) SetMsg(v ConvoMsg) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewMsg sets the msg field to a newly
// allocated ConvoMsg struct, preferring placement in s's segment.
func (s EntryMix_addConvoMsg_Params) NewMsg() (ConvoMsg, error) {
	ss, err := NewConvoMsg(s.Struct.Segment())
	if err != nil {
		return ConvoMsg{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// EntryMix_addConvoMsg_Params_List is a list of EntryMix_addConvoMsg_Params.
type EntryMix_addConvoMsg_Params_List struct{ capnp.List }

// NewEntryMix_addConvoMsg_Params creates a new list of EntryMix_addConvoMsg_Params.
func NewEntryMix_addConvoMsg_Params_List(s *capnp.Segment, sz int32) (EntryMix_addConvoMsg_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return EntryMix_addConvoMsg_Params_List{l}, err
}

func (s EntryMix_addConvoMsg_Params_List) At(i int) EntryMix_addConvoMsg_Params {
	return EntryMix_addConvoMsg_Params{s.List.Struct(i)}
}

func (s EntryMix_addConvoMsg_Params_List) Set(i int, v EntryMix_addConvoMsg_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s EntryMix_addConvoMsg_Params_List) String() string {
	str, _ := text.MarshalList(0xfd26198720563ad2, s.List)
	return str
}

// EntryMix_addConvoMsg_Params_Promise is a wrapper for a EntryMix_addConvoMsg_Params promised by a client call.
type EntryMix_addConvoMsg_Params_Promise struct{ *capnp.Pipeline }

func (p EntryMix_addConvoMsg_Params_Promise) Struct() (EntryMix_addConvoMsg_Params, error) {
	s, err := p.Pipeline.Struct()
	return EntryMix_addConvoMsg_Params{s}, err
}

func (p EntryMix_addConvoMsg_Params_Promise) Msg() ConvoMsg_Promise {
	return ConvoMsg_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

type EntryMix_addConvoMsg_Results struct{ capnp.Struct }

// EntryMix_addConvoMsg_Results_TypeID is the unique identifier for the type EntryMix_addConvoMsg_Results.
const EntryMix_addConvoMsg_Results_TypeID = 0xb2f0acb096c0cff7

func NewEntryMix_addConvoMsg_Results(s *capnp.Segment) (EntryMix_addConvoMsg_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EntryMix_addConvoMsg_Results{st}, err
}

func NewRootEntryMix_addConvoMsg_Results(s *capnp.Segment) (EntryMix_addConvoMsg_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EntryMix_addConvoMsg_Results{st}, err
}

func ReadRootEntryMix_addConvoMsg_Results(msg *capnp.Message) (EntryMix_addConvoMsg_Results, error) {
	root, err := msg.RootPtr()
	return EntryMix_addConvoMsg_Results{root.Struct()}, err
}

func (s EntryMix_addConvoMsg_Results) String() string {
	str, _ := text.Marshal(0xb2f0acb096c0cff7, s.Struct)
	return str
}

func (s EntryMix_addConvoMsg_Results) Status() uint8 {
	return s.Struct.Uint8(0)
}

func (s EntryMix_addConvoMsg_Results) SetStatus(v uint8) {
	s.Struct.SetUint8(0, v)
}

// EntryMix_addConvoMsg_Results_List is a list of EntryMix_addConvoMsg_Results.
type EntryMix_addConvoMsg_Results_List struct{ capnp.List }

// NewEntryMix_addConvoMsg_Results creates a new list of EntryMix_addConvoMsg_Results.
func NewEntryMix_addConvoMsg_Results_List(s *capnp.Segment, sz int32) (EntryMix_addConvoMsg_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return EntryMix_addConvoMsg_Results_List{l}, err
}

func (s EntryMix_addConvoMsg_Results_List) At(i int) EntryMix_addConvoMsg_Results {
	return EntryMix_addConvoMsg_Results{s.List.Struct(i)}
}

func (s EntryMix_addConvoMsg_Results_List) Set(i int, v EntryMix_addConvoMsg_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s EntryMix_addConvoMsg_Results_List) String() string {
	str, _ := text.MarshalList(0xb2f0acb096c0cff7, s.List)
	return str
}

// EntryMix_addConvoMsg_Results_Promise is a wrapper for a EntryMix_addConvoMsg_Results promised by a client call.
type EntryMix_addConvoMsg_Results_Promise struct{ *capnp.Pipeline }

func (p EntryMix_addConvoMsg_Results_Promise) Struct() (EntryMix_addConvoMsg_Results, error) {
	s, err := p.Pipeline.Struct()
	return EntryMix_addConvoMsg_Results{s}, err
}

const schema_a1ac1f9011521afa = "x\xda\x84\x92=\x88\x13A\x14\xc7\xdf\x9b\xd9\xcd\x9eB" +
	"\xc8.\xabE\xfc\xc0\x0fN\xe1\x04O\x0f\xb1\x89E\x82" +
	"\x87VF\xb3Q\x14,\xc4\xbdd\\\"f6\xb73" +
	"\xd1\\\xa3\x18\x84\xa0\x85h\xa1\x88`!\x88\x10\xb8B" +
	"\x05\xadml\x0eD\x14\xae\xb0\xb7\xb2\x10\xe5\x0a\xbf\x90" +
	"\x95\xd98\xb7\xeb\x07^7\xb0\xff\xf7\xff\xff\xde\x7f\xdf" +
	"\xee\x83X!S\xe6\xc0\x04\xf0*f.~x\xb2\xff" +
	"a\x15\xbbz\x0b<\x1b1\xfe\xb6\xae\xee\xdc\xd84\x7f" +
	"\x1f\x0c\x0b\xc0\x1d\x92\xf7\xeeS\xa2^\x8fI\x190\xbe" +
	"3<\xf2\xe5\xd9\xec\xd1!8E\x84D\xb2\xe7-\xe9" +
	"#\x18\xf1\xe7W\xcfo?\x9a\xff\xf8\x04\xbc\"\xeaO" +
	"/\xc8Y\x04t_'\xa3\xd7\x97\x16\xc9\xa9\xafK/" +
	"G\xa3&*\xc1'rM\x09\x90*\xc1\x85\xbd\xeb\xf7" +
	"\x1dzp\xe5\x1d86M1\x00\xdd-t\xc1\xddI" +
	"\x15\xc4\x04\x1d\xb8\x97\xd5+\xe6\xa7/\x9eX\xdc\xf6]" +
	"\x893\xcc\x89\xab\xdb\xa2\x0bn7\xd1\xcf&\xc6oJ" +
	"\xc77\x0f\x8a\xdb\x7fd\x93o\xd2\x19\x95|\x8f\x96\xa1" +
	"\x19G\x9d\xc6.\xc6eD\xe6&\x1b~\x87wJ\xd5" +
	"V\x8f39\x1d\x16\xf8\x99VPC\xf4\x0cj\x00\x18" +
	"\x08\xe0\xe4\xef\x02x6Eo\x03\xc1X\xb0F\xc8\x9b" +
	"\xe2\x18\x86\x87YO\xd6\xc3.\xe5M\xb4\x80\xa0\x05\xb8" +
	"\xec\xbaZ\xbb\x1e\xe02\x9a\xab\xb6z\x93\x01\x93:A" +
	"\x05\x8c\xd7\xfc\xc8o\x0b\xd0\x03\x7f\xe9\xfdfs:\xe4" +
	"\xe7\xc3\xaa\x08\xc6\xebL\x14\xba\xe7\xa4\xc8\"\x95\x00\xbc" +
	"1\x8a\xde\x1a\x82e!}\xd9\x15\x98\x03\x82\xb9\x0c\x84" +
	"\xb9\"D\x9d\x09\xe5\x0b\x90u\xde\x91:\x17\xdaL\xfa" +
	"h\xa7\xe7\x02\x88v&\x81\xfc\x99\x00\xa0\x9a\x1b\xa3&" +
	"\xc0\xf2\xdd\xa0\xbe\x02g\xaa\x0f\xc4\x99\xb00\xfd=\xa8" +
	"O\xc8\xd98\x03\xc4Yk\xc5\x1a\x11\x7f1B\x05c" +
	"\xdd\x05XU\x11T\xb0\x86\xff \xd0e\x8d\x082\xeb" +
	"\xecO\xd7\xb9\xd4\x08\xb9d\\b\x1e\x08\xe63{\x18" +
	"\xff\xad\xbf\xe6G\x96\xdf\xfe\xad\xfd\xad\xa9\xa9\xd5\x16\x01" +
	"\xda\xe9q\x8e*\xfa\x19\x00\x00\xff\xff\xf5h\xfde"

func init() {
	schemas.Register(schema_a1ac1f9011521afa,
		0x95896509ee825aa6,
		0xa95371b6f84fa998,
		0xb2f0acb096c0cff7,
		0xcdf3f95e02d5f38e,
		0xe484a44c3b1b3577,
		0xe4fb25d5577e606e,
		0xfd26198720563ad2)
}
